default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  user: valya
  password: valya

development:
  <<: *default
  database: sample_app_development

test: &test
  <<: *default
  database: sample_app_test

production:
  adapter: postgresql
  database: sample_app_production
  pool: 5
  timeout: 5000
cucumber:
  <<: *test
